# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use the official Hugo setup action
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Runs a set of commands using the runners shell
      - name: Display hugo version
        run: |
          hugo version
      
      # Setup Git in public folder
      - name: Setup Git in public folder
        run: |
          mkdir public
          cd public 
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.GIT_SECRET_KEY }}"
          git config --global user.email "bhar1red@gmail.com"
          git config --global user.name "Bargav Kondapu"  
          git init 
          git remote add origin git@github.com:bhar1red/bhar1red.github.io.git 
          git pull origin master 
          cd ..     
          
      
      # Hugo deploy to public folder
      - name: hugo Deploy
        run: |
          hugo -D
          ls -l
          
      - name: Add ssh and Deploy public folder
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.GIT_SECRET_KEY }}"
          cd public
          git status
          ls -l 
          git add .
          git commit -m "Site deploy"
          git push -u origin master
        
          
          
      
